"""Read the binary vectors generated by the integrated OpenMP executable."""

from __future__ import annotations

import struct
from pathlib import Path

import numpy as np


HEADER = struct.Struct("<8sII")
MAGIC = b"YAWNMLP"


def load_preprocessed_split(path: str | Path) -> tuple[np.ndarray, np.ndarray]:
    with Path(path).open("rb") as binary_file:
        magic, count, features = HEADER.unpack(binary_file.read(HEADER.size))
        if magic.rstrip(b"\0") != MAGIC:
            raise ValueError(f"Formato no válido: {path}")
        labels = np.frombuffer(binary_file.read(count * 4), dtype="<i4").copy()
        vectors = np.frombuffer(binary_file.read(count * features * 4), dtype="<f4").copy()
    return vectors.reshape(count, features), labels
